
package com.transunion.pokemon_app.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PokemonPort", targetNamespace = "http://transunion.com/pokemonapp/soap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PokemonPort {


    /**
     * 
     * @param buscarPokemonesRequest
     * @return
     *     returns com.transunion.pokemon_app.soap.BuscarPokemonesResponse
     */
    @WebMethod(operationName = "BuscarPokemones")
    @WebResult(name = "BuscarPokemonesResponse", targetNamespace = "http://transunion.com/pokemonapp/soap", partName = "BuscarPokemonesResponse")
    public BuscarPokemonesResponse buscarPokemones(
        @WebParam(name = "BuscarPokemonesRequest", targetNamespace = "http://transunion.com/pokemonapp/soap", partName = "BuscarPokemonesRequest")
        BuscarPokemonesRequest buscarPokemonesRequest);

}
